#!/usr/bin/env python3
"""
Quick setup script to configure frontend and backend URLs
"""

import os
import sys

print("=" * 60)
print("🔧 CoreDent URL Configuration Helper")
print("=" * 60)

# Get backend URL
print("\n1️⃣ Backend Configuration")
print("-" * 60)
backend_url = input("Enter your Railway BACKEND URL (e.g., https://coredent-api-production.up.railway.app): ").strip()

if not backend_url:
    print("❌ Backend URL is required!")
    sys.exit(1)

# Remove trailing slash
backend_url = backend_url.rstrip('/')

# Ensure https
if not backend_url.startswith('http'):
    backend_url = f"https://{backend_url}"

print(f"✅ Backend URL: {backend_url}")

# Get frontend URL
print("\n2️⃣ Frontend Configuration")
print("-" * 60)
frontend_url = input("Enter your FRONTEND URL (e.g., https://coredent.vercel.app or http://localhost:5173): ").strip()

if not frontend_url:
    print("❌ Frontend URL is required!")
    sys.exit(1)

# Remove trailing slash
frontend_url = frontend_url.rstrip('/')

# Ensure protocol
if not frontend_url.startswith('http'):
    frontend_url = f"https://{frontend_url}"

print(f"✅ Frontend URL: {frontend_url}")

# Create frontend .env.local
print("\n3️⃣ Creating Frontend Configuration")
print("-" * 60)

frontend_env_content = f"""# CoreDent Frontend Configuration
# Auto-generated by setup_urls.py

# Backend API URL
VITE_API_BASE_URL={backend_url}/api/v1

# Development settings
VITE_DEV_BYPASS_AUTH=false
VITE_DEBUG=false
"""

frontend_env_path = "coredent-style-main/.env.local"
try:
    with open(frontend_env_path, 'w') as f:
        f.write(frontend_env_content)
    print(f"✅ Created {frontend_env_path}")
except Exception as e:
    print(f"❌ Failed to create {frontend_env_path}: {e}")

# Show backend environment variables
print("\n4️⃣ Backend Environment Variables")
print("-" * 60)
print("Add these to your Railway backend service:")
print()
print(f"CORS_ORIGINS={frontend_url},http://localhost:5173")
print(f"FRONTEND_URL={frontend_url}")
print()
print("Steps:")
print("1. Go to Railway dashboard")
print("2. Click on your backend service")
print("3. Go to 'Variables' tab")
print("4. Add/Update the variables above")
print("5. Click 'Deploy' to restart")

# Summary
print("\n" + "=" * 60)
print("✅ Configuration Complete!")
print("=" * 60)
print()
print("Frontend Configuration:")
print(f"  File: {frontend_env_path}")
print(f"  API URL: {backend_url}/api/v1")
print()
print("Backend Configuration (add to Railway):")
print(f"  CORS_ORIGINS: {frontend_url},http://localhost:5173")
print(f"  FRONTEND_URL: {frontend_url}")
print()
print("Next Steps:")
print("1. Update Railway backend variables (see above)")
print("2. Restart frontend: cd coredent-style-main && npm run dev")
print("3. Test login at: {frontend_url}")
print()
print("Test backend health:")
print(f"  curl {backend_url}/health")
print()
print("=" * 60)
