"""
Vendor Service
Automated inventory reordering and contract management
"""

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_, func
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from uuid import UUID

from app.models.inventory import (
    InventoryItem, ReorderRule, PurchaseOrder, PurchaseOrderItem,
    VendorContract, VendorInvoice, Supplier, InventoryAlert, InventoryAlertType
)
from app.models.user import User

import logging
logger = logging.getLogger(__name__)


class VendorService:
    """Business logic for vendor automation"""

    @staticmethod
    async def check_inventory_and_reorder(db: AsyncSession, practice_id: UUID) -> Dict[str, Any]:
        """Check inventory levels against rules and trigger reorders or alerts"""
        
        # 1. Get all active reorder rules for the practice
        result = await db.execute(
            select(ReorderRule).where(
                and_(
                    ReorderRule.practice_id == practice_id,
                    ReorderRule.is_active == True,
                )
            )
        )
        rules = result.scalars().all()
        
        actions_taken = {
            "alerts_created": 0,
            "purchase_orders_created": 0,
            "items_processed": []
        }

        # Track which items need orders by supplier
        orders_by_supplier = {}

        for rule in rules:
            # Check item quantity
            item_result = await db.execute(select(InventoryItem).where(InventoryItem.id == rule.item_id))
            item = item_result.scalar_one_or_none()
            
            if not item:
                continue
                
            if item.current_quantity <= rule.trigger_quantity:
                # Triggered!
                actions_taken["items_processed"].append(item.name)
                
                if rule.auto_approve and rule.supplier_id:
                    # Queue for PO generation
                    if rule.supplier_id not in orders_by_supplier:
                        orders_by_supplier[rule.supplier_id] = []
                    orders_by_supplier[rule.supplier_id].append({
                        "item": item,
                        "quantity": rule.reorder_quantity
                    })
                else:
                    # Just create an alert
                    alert = InventoryAlert(
                        practice_id=practice_id,
                        item_id=item.id,
                        alert_type=InventoryAlertType.REORDER_POINT,
                        message=f"Stock for {item.name} is {item.current_quantity}. Reorder threshold is {rule.trigger_quantity}."
                    )
                    db.add(alert)
                    actions_taken["alerts_created"] += 1
                
                rule.last_triggered_at = datetime.now(timezone.utc)

        # Generate POs for auto-approve items
        for supplier_id, items_to_order in orders_by_supplier.items():
            # Create a new PO
            po_number = f"PO-AUTO-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-{str(supplier_id)[:4]}"
            po = PurchaseOrder(
                practice_id=practice_id,
                supplier_id=supplier_id,
                order_number=po_number,
                status="pending",
                internal_notes="Auto-generated by Reorder Rules engine"
            )
            db.add(po)
            await db.flush()  # get po.id
            
            subtotal = 0.0
            
            # Add items
            for order_item in items_to_order:
                item = order_item["item"]
                quantity = order_item["quantity"]
                cost = float(item.unit_cost or 0)
                
                po_item = PurchaseOrderItem(
                    order_id=po.id,
                    item_id=item.id,
                    quantity_ordered=quantity,
                    unit_cost=cost,
                    total_cost=cost * quantity
                )
                db.add(po_item)
                subtotal += (cost * quantity)
                
            po.subtotal = subtotal
            po.total = subtotal  # Add tax/shipping later if needed
            actions_taken["purchase_orders_created"] += 1

        await db.commit()
        return actions_taken
